# Generated by Django 4.1.13 on 2023-12-27 03:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_bookinstance_borrower"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookinstance",
            options={
                "ordering": ["due_back"],
                "permissions": (("can_mark_returned", "Set book as returned"),),
            },
        ),
    ]
