# Generated by Django 4.1.13 on 2023-12-27 04:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_alter_bookinstance_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={
                "ordering": ["last_name", "first_name"],
                "permissions": (("can_mark_returned", "Set book as returned"),),
            },
        ),
    ]
